name: Bench Presentations

# Controls when the action will run. 
# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  benchmark:
    name: Benchmark Presentations
    strategy:
      matrix:
        workload: [ 'presentations', 'stocks' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: dev

        - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Build artifacts
          run: mvn clean install

        - name: Run Benchmark
          run: java -jar target/benchmarks.jar -i 4 -wi 4 -f 1 -r 2 -w 2 -rff results.csv -rf csv -tu ms ${{ matrix.workload }}

        - name: Upload results
          uses: actions/upload-artifact@v2
          with:
            name: bench-results-${{ matrix.os }}-${{ matrix.workload }}
            path: ./results.csv
